name: Build and Zip Firefox Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v6
        with:
          version: 10.19.0
          cache: true
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: pnpm install

      - name: Build Firefox
        run: pnpm run build:firefox

      - name: Upload Firefox extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: graze-firefox
          path: .output/firefox-mv2
