name: Build and Zip Firefox Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: pnpm/setup/@v1
        name: Install pnpm
        with:
          version: 11
          install: false
          runtime: node@22
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build Firefox
        run: pnpm run build:firefox

      - name: Upload Firefox extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: graze-firefox
          path: .output/firefox-mv2
