name: Build and Zip Firefox Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm

      - name: Build Firefox
        run: pnpm build:firefox

      - name: Upload Firefox extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: graze-firefox
          path: dist_firefox
